import Component from '@glimmer/component';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';
import { htmlSafe } from '@ember/template';
import { Button, Collapsible } from 'frontile';

export interface Signature {
  Args: {
    /**
     * Pre-highlighted `<code>` markup from
     * `app/components/homepage/snippets.ts`, which is generated by
     * `site/lib/generate-homepage-snippets.mjs`. Nothing on this page
     * tokenises in the browser.
     */
    html?: string;
    /** Plain text, for the `@isTerminal` variant — a command, not source. */
    code?: string;
    /** Filename or caption shown in the window chrome. */
    label?: string;
    /** Render a shell prompt rather than highlighted source. */
    isTerminal?: boolean;
    /** Put the body behind a toggle, for snippets long enough to dominate. */
    isCollapsible?: boolean;
  };
  Element: HTMLDivElement;
}

/**
 * A code "window": dark panel, chrome dots, a soft primary glow, and syntax
 * highlighting baked in at build time.
 *
 * Why the panel stays dark in both themes: the surface uses the dedicated
 * `--color-code-*` tokens rather than the theme's scheme-dependent neutrals,
 * which invert between light and dark. The Shiki markup inside carries both
 * `--shiki-light` and `--shiki-dark`, so `app/styles/docfy-code-block.css`
 * pins these panels to the dark set regardless of the visitor's scheme.
 *
 * Long snippets take `@isCollapsible`, which uses Frontile's own Collapsible,
 * so a forty-line config does not out-weigh the thing it explains.
 */
export default class CodePanel extends Component<Signature> {
  @tracked isOpen = false;

  get toggleLabel(): string {
    return this.isOpen ? 'Hide code' : 'Show code';
  }

  get markup(): ReturnType<typeof htmlSafe> {
    return htmlSafe(this.args.html ?? '');
  }

  @action
  toggle(): void {
    this.isOpen = !this.isOpen;
  }

  <template>
    {{! Dark in both schemes via the --color-code-* tokens, lifted by a real
        offset glow drawn from the accent rather than a zero-offset halo. }}
    <div
      class="code-panel overflow-hidden rounded-xl border border-code-border bg-code-surface shadow-[0_18px_40px_-24px_var(--color-primary-soft),0_2px_10px_-6px_var(--color-surface-overlay-firm),inset_0_1px_0_rgb(255_255_255/0.04)]"
      ...attributes
    >
      <div
        class="flex items-center gap-3 border-b border-code-border bg-code-chrome px-3.5 py-2"
      >
        {{! Traffic-light chrome. The status hues are used as *illustration*
            here — they depict a window's controls and report no state, which is
            why this is not a breach of the status-means-status rule. They are
            decorative, aria-hidden, and never the only carrier of meaning.
            Written per dot rather than as :nth-child so the colour is visible
            where the markup is. }}
        <span class="flex flex-none gap-1.5" aria-hidden="true">
          <span class="size-2.5 rounded-full bg-danger"></span>
          <span class="size-2.5 rounded-full bg-warning"></span>
          <span class="size-2.5 rounded-full bg-success"></span>
        </span>

        {{#if @label}}
          <span
            class="min-w-0 truncate font-code text-code-sm text-neutral"
          >{{@label}}</span>
        {{/if}}

        {{#if @isCollapsible}}
          <span class="ml-auto flex-none text-code-ink">
            <Button
              @variant="plain"
              @size="xs"
              @onPress={{this.toggle}}
              aria-expanded={{if this.isOpen "true" "false"}}
            >{{this.toggleLabel}}</Button>
          </span>
        {{/if}}
      </div>

      {{#if @isTerminal}}
        <pre
          class="m-0 overflow-x-auto px-5 py-[1.125rem] font-code text-code-md text-code-ink"
        ><span
            class="select-none text-code-prompt"
            aria-hidden="true"
          >$</span> {{@code}}</pre>
      {{else if @isCollapsible}}
        <Collapsible @isOpen={{this.isOpen}}>
          <pre
            class="m-0 overflow-x-auto px-5 py-[1.125rem] font-code text-code-sm text-code-ink"
          >{{this.markup}}</pre>
        </Collapsible>
      {{else}}
        <pre
          class="m-0 overflow-x-auto px-5 py-[1.125rem] font-code text-code-sm text-code-ink"
        >{{this.markup}}</pre>
      {{/if}}
    </div>
  </template>
}
